-- Audit-ready source-to-target control evidence generated by ETL.
SELECT control_name, source_value, target_value, difference, status
FROM etl_control
ORDER BY control_name;

-- Eligibility reconciliation: loaded claims whose service date is outside coverage.
SELECT f.claim_id, f.member_id, f.service_date,
       e.enrollment_start, e.enrollment_end,
       CASE WHEN f.service_date BETWEEN e.enrollment_start AND e.enrollment_end
            THEN 'ELIGIBLE' ELSE 'OUTSIDE_ENROLLMENT' END AS eligibility_status
FROM fact_claim f
JOIN fact_enrollment e ON e.member_id = f.member_id
WHERE f.service_date NOT BETWEEN e.enrollment_start AND e.enrollment_end
ORDER BY f.service_date;

-- Loaded and quarantined financial populations reconcile to source controls.
WITH target_amounts AS (
    SELECT SUM(claim_amount_cents) AS billed_cents,
           SUM(allowed_amount_cents) AS allowed_cents,
           SUM(paid_amount_cents) AS paid_cents
    FROM (
        SELECT claim_amount_cents, allowed_amount_cents, paid_amount_cents FROM fact_claim
        UNION ALL
        SELECT claim_amount_cents, allowed_amount_cents, paid_amount_cents FROM claim_quarantine
    )
)
SELECT ROUND(billed_cents / 100.0,2) AS reconciled_billed_amount,
       ROUND(allowed_cents / 100.0,2) AS reconciled_allowed_amount,
       ROUND(paid_cents / 100.0,2) AS reconciled_paid_amount
FROM target_amounts;
